### ISSUE TITLE
iisc_start.10 needs to use can_have_corp trigger

### ISSUE THREAD

**Issue by fireinthedisco** [calniotrey/space-corp#43]
https://github.com/calniotrey/space-corp/blob/bb9645088267d666737e3f88fad1abfe1eaaf0aa/events/iisc_start_events.txt#L6-L11

If I understand correctly, this is initial setup for a country who can have space corps, in which case we will want to use the can_have_corps trigger instead of checking country type is default.

**Comment by calniotrey** [comment]
Yep good idea
